[package]
name = "printf"
version = "0.1.0"
authors = ["Richard Dodd <richard.o.dodd@gmail.com>"]
build = "./build.rs"

[dependencies]
libc = "*"

[dev-dependencies]
printf_helper = { path = "../printf_helper" }

[build-dependencies]
gcc = "*"
