[package]
name = "libalpm"
version = "0.1.0"
authors = ["Richard Dodd <richard.o.dodd@gmail.com>"]

[dependencies]
alpm-sys = "*"
printf = "*"
libc = "*"
url = "*"
lazy_static = "*"

[dev-dependencies]
term = "*"
curl = "*"
